FROM python:3
WORKDIR /GraphNAS
COPY ./requirements.txt /GraphNAS
# speed up use chinese source
#RUN pip config set global.index-url https://mirrors.aliyun.com/pypi/simple/
#RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install -r requirements.txt
#COPY . .
#CMD [ "python", "./main.py" ]
