FROM python:3
WORKDIR /GraphNAS
COPY ./requirements.txt /GraphNAS
# speed up use chinese source
#RUN pip config set global.index-url https://mirrors.aliyun.com/pypi/simple/
#RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip install -r requirements.txt
RUN pip install https://download.pytorch.org/whl/cpu/torch-1.0.1.post2-cp37-cp37m-linux_x86_64.whl
#COPY . .
#CMD [ "python", "./main.py" ]
